### PR TITLE
log4j2.xml should not be included in the jar

### PR DESCRIPTION
**Pull request by fxbonnet**
Hi,
I had an issue on my project with the log4j2.xml file that is included in podam.jar
I think this file is useful for testing purposes but it should not be included in the jar as each project is supposed to have its own log configuration. So I moved the file to src/test/java.
In addition I noticed that some dependencies were not used so I tried to remove them or change the scope in order to reduce the number of dependencies with compile or runtime scope (this should help avoiding some conflicts in projects that are using podam).
Before the fix, maven dependency:analyze gave the following:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    org.slf4j:slf4j-api:jar:1.7.12:compile
[WARNING]    org.springframework:spring-messaging:jar:4.1.4.RELEASE:compile
[WARNING]    xml-apis:xml-apis:jar:1.4.01:test
[WARNING] Unused declared dependencies found:
[WARNING]    org.apache.logging.log4j:log4j-api:jar:2.3:compile
[WARNING]    org.apache.logging.log4j:log4j-core:jar:2.3:compile
[WARNING]    org.apache.logging.log4j:log4j-jcl:jar:2.2:compile
[WARNING]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile
[WARNING]    org.springframework:spring-beans:jar:4.1.6.RELEASE:compile
[WARNING]    org.springframework:spring-context-support:jar:4.1.6.RELEASE:compile
[WARNING]    org.springframework:spring-expression:jar:4.1.6.RELEASE:compile
[WARNING]    org.easytesting:fest-assert:jar:1.4:test
[WARNING]    com.googlecode.lambdaj:lambdaj:jar:2.3.3:test
```
And after the fix:
```
[WARNING] Unused declared dependencies found:
[WARNING]    org.apache.logging.log4j:log4j-core:jar:2.3:test
[WARNING]    org.apache.logging.log4j:log4j-jcl:jar:2.2:test
[WARNING]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:test
```
(no more warning, at least for compile and runtime scopes)

### CODE REVIEW

**Comment by daivanov** [comment]
Hi! Why log4j-jcl is needed?

**Comment by fxbonnet** [comment]
It was already there, I did not add it.
I guess the goal is to redirect all the logs to log4j2 during the unit tests. As podam uses libraries that depend on slf4j and commons-logging, we need both log4j-slf4j-impl and log4j-jcl

**Comment by daivanov** [comment]
According to `mvn dependency:tree` there is nothing depending on commons-logging expect of log4j-jcl itself.

**Comment by fxbonnet** [comment]
Looking at the dependency hyerarchy in Eclipse, I see that commons-logging is used by spring-core, serenity-core and serenity-junit.
I have just tried to remove it and launch a mvn install and it still works but it adds a bunch of info messages from springframework classes in the logs. Therefore I think it is better to keep this dependency.

**Comment by daivanov** [comment]
Then I don't know what `mvn dependency:tree` shows.

**Comment by fxbonnet** [comment]
Try ```mvn dependency:tree -Dverbose```
Without this ```verbose``` parameter, maven does not show the dependencies that were omitted during resolution because they were duplicate or in conflict.

**Comment by mtedone** [comment]
Why would log4j create problems to your project? If you're using log4j as
well you could define a logger and decide what to do with podam logging.
Podam uses log4j not only for testing but during its execution.

I'll have a look at other dependencies and see if I can incorporate some of
your changes.

Regards,

**Comment by daivanov** [comment]
This is how it works for libraries (including podam at the moment)

    library <-> slf4j <-> logger implementation

Library explicitely uses slf4j API and the latter performs logger discovery during runtime and uses found logger through reflection. This gives possibility to library users to use log4j, log4j2, logback or JCL in their applications without any changes or configuration on library side. At the moment log4j2 is a test dependency and used only for test execution, so inclusion its configuration into release package isn't proper thing. It won't affect non-log4j2 users, but it might conflict with log4j2 user's own configurations.

**Comment by fxbonnet** [comment]
Podam does not require log4j during its execution, in fact I can replace it in my project by any other slf4j binding but currently this is a little tricky because Podam declares a dependency to log4j, I have to deal with conflicts and add some exclusions to my pom.xml

Here is the recommendation taken from slf4j documentation:
> ```BASIC RULE``` **Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api**. When a library declares a transitive dependency on a specific binding, that binding is imposed on the end-user negating the purpose of SLF4J. Note that declaring a non-transitive dependency on a binding, for example for testing, does not affect the end-user.

http://www.slf4j.org/manual.html#libraries

**Comment by mtedone** [comment]
Alright I'll merge the pull request over the weekend.

**Pull request merged**
