### PR TITLE
Added conversion of boolean primitive type to Boolean

### PR DESCRIPTION
**Pull request by ledinscak**
Don't know if you missed it on purpose, but method name suggests it should be there :-)

### CODE REVIEW

**Comment by daivanov** [comment]
Hi,

  Could you please explain your patch?

Thanks, Daniil

**Comment by ledinscak** [comment]
Hello, I just saw method signature that takes primitive type, and noticed that boolean (primitive type) does not exist and does not do Boxing to Boolean.class. Sorry but I did not check where method is beeing invoked in rest of app. Maybe I am missing something there, I just wanted to get your attention that maybe boolean was forgotten there.

**Comment by daivanov** [comment]
I originally confused this pull request with spam. Sorry about that. Now it is merged, thank you.

**Comment by ledinscak** [comment]
No problem ;-)

**Pull request closed without merging**
