### PR TITLE
 In the presence of multiple constructors (default + full), give users the ability to choose which one to use

### PR DESCRIPTION
**Pull request by daivanov**
Proposed for Issue #75 
Now there constructor comparator can be set to AbstractRandomDataProviderStrategy.
There are two default implementations:
ConstructorLightFirstComparator and ConstructorHeavyFirstComparator.
Aditionally PODAM users may custom one.

### CODE REVIEW

**Comment by mtedone** [comment]
What's the default? Also, it would be nice to have a setConstructorStrategy(boolean full) in the DataProviderStrategy so that users can change the strategy between executions. The default strategy should be to use the full constructor

**Comment by daivanov** [comment]
Default is the same as before `ConstructorLightFirstComparator`. Changing that will cause many failing tests and performance drop: most of the POJOs can be created with simple constructor and then filled through setters.

Using boolean switch for constructor strategy selection assumes that there can be only two strategies. However, there is infinite ways of ordering constructors. One of the example, could be random shuffling an array.

There is a problem with adding this parameter to `DataProviderStrategy` because the latter just implements `sort(Constructor<?>[] constructors)`. Which allows any possible strategy implementation. More specific implementation based on `Comparator` is added `AbstractDataProviderStrategy` and it's singleton descendant `RandomDataProviderStrategy`.

**Comment by mtedone** [comment]
Daniil I find too strict. Podam's mission is to fill object with dummy data
to aid (mainly) unit testing. From a user perspective, I'd like to use
Podam to fill asany data as possible. If changing the default will break
tests we should be fixing them (I can't think that'll be too hard to do,
probably just removing / updating some assertions). Also there is too much
flexibility around comparators. Typically users will want either the full
strategy or the default strategy so we slcpuld implement this Boolean
strategy in the strategy.

**Comment by daivanov** [comment]
Producing POJO is a very intelligent task and every now and then default strategy fails and it's required to alter it. So it cannot be too much flexibility in this matter.

For example, `BigInteger(int bitLength, int certainty, Random rnd)` cannot succeed with default PODAM strategy, if constructor with the most arguments will be chosen first.

Better describe use-case, which resulted in Issue #75.

**Comment by mtedone** [comment]
Podam should be intelligent enough to try the fullest constructor first, then if that doesn’t work, it should try the one with less arguments and so on until, if none of the other constructors work, it will choose the default one. 

Example: 

1: BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(int,%20int,%20java.util.Random)>(int bitLength, int certainty, Random <http://docs.oracle.com/javase/7/docs/api/java/util/Random.html> rnd)

2: BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(int,%20byte[])>(int signum, byte[] magnitude)
   BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(int,%20java.util.Random)>(int numBits, Random <http://docs.oracle.com/javase/7/docs/api/java/util/Random.html> rnd)
   BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(java.lang.String,%20int)>(String <http://docs.oracle.com/javase/7/docs/api/java/lang/String.html> val, int radix)

3: BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(byte[])>(byte[] val)
   BigInteger <http://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(java.lang.String)>(String <http://docs.oracle.com/javase/7/docs/api/java/lang/String.html> val)

Podam should start with 1. If it can’t build, the first constructor within 2 that succeeds should be used. If that doesn’t work, the fist constructor within 3 should be used and so on until the last choice should be the default constructor (if it exists). This is a very good test case that we should be writing when implement this strategy. The test cases should demonstrate Podam’s ability to “scale down” to the most useful (fullest) constructor.

Regards,
M.

**Comment by mtedone** [comment]
I’ve updated https://github.com/mtedone/podam/issues/75 <https://github.com/mtedone/podam/issues/75> with the requirements. 

Regards,
M.

**Comment by daivanov** [comment]
Yes, but after trying 1 for a while JRE will crash.

**Comment by mtedone** [comment]
I don’t understand Daniil. We should try 1 only once and if it doesn’t work we should move to another constructor. Why would JRE crash?

**Comment by daivanov** [comment]
If you want to try it yourself, let me know where you want code to be merged.

**Comment by mtedone** [comment]
Can you create a branch called marco-test?

**Comment by daivanov** [comment]
Done: https://github.com/mtedone/podam/tree/marco-test

**Comment by mtedone** [comment]
OK, I can see what you mean. Doing the full constructor on a complex tree might crash the JVM. I think we’ve found a good balance by setting light as default but giving options to users to set it to heavy if required. 

Observations: 

1) I’d suggest we put a manufacturePojoWithFullData method in the PodamFactory interface. This would set the heavy comparator in the strategy, delegating then the work to manufacturePojo and will make the use of Podam easier (users will still need to write just one line to get their full object) as opposed to them having to get the strategy, set the comparator and set the strategy in the factory. 

2) The test for this scenario (in Immutable Pojo), should ideally demonstrate also the fallback from constructor with two arguments to constructor with one and then on default. The way to do this would be to find (or create) a class with three constructors (2 args, 1 arg and default), where non default arguments could not be created. One way to achieve this could be to throw an exception from the constructor of the “unconstructable” class. 

3) We should update the html documentation saying that by default Podam creates lightweight constructors and instructions on how to set full constructor strategy.

Then I’m happy for you to merge your changes to master and we should release version 5.0.0.RELEASE as we’re changing the interface.

Regards,

**Pull request closed without merging**
