### PR TITLE
Determines generic type parameters if class implements list<?> or map<?,?>

### PR DESCRIPTION
**Pull request by kirikaza**

### CODE REVIEW

**Comment by daivanov** [comment]
Hi Kirill!

  Do you have an examples to reproduce this problem?

Thanks, Daniil

**Comment by kirikaza** [comment]
Prepared example for List<>: https://gist.github.com/kirikaza/a2aefe6fbfbec073b847

**Comment by mtedone** [comment]
Hi, I'm undergoing a major refactoring of the code on branch issue111. I'd suggest to issue your pull request there or to wait until I rebase master once I've completed the refactoring.

**Comment by daivanov** [comment]
Thank you, Kirill for finding such tricky issue. The root-cause for the problem is collection/map has default value (which is improperly handled).

**Comment by kirikaza** [comment]
Yesterday I found that the provided fixes are not complete. If you insert yet another class with type variables, my fix can't determine which types are hidden by these variables. There is a gist with sample: https://gist.github.com/kirikaza/d5101c6f1c6513bd6e22

**Comment by kirikaza** [comment]
Prepared better and clearer solution in #115. I afraid it would conflict with your refactoring.

**Comment by mtedone** [comment]
Duplicated by #115

**Pull request closed without merging**
